### ISSUE TITLE
Create a Devcontainer

### ISSUE THREAD

**Issue by kvncont** [kvncont/report-hub#2]
# New Feature

## Description

We require a devcontainer that ease the setup  of the development environment

## Tasks

- [ ] Setup de tools (feature, dockerfile)
- [ ] Setup the extensions and settings
- [ ] Test the devcontainer in different OS (macOs, Windows)

### Tools need it:
* Python 3.12
* Terraform (latest version)
* Azure CLI (latest version)

## Dependencies

N/A

**Comment by kvncont** [comment]
This issue was resolve with PR #6
